### ISSUE TITLE
Cant find video problem 

### ISSUE THREAD

**Issue by snb0169** [Xi-Plus/watch-along-stopwatch#1]
![Untitled](https://github.com/user-attachments/assets/3ae2dbd2-7bc0-4ade-9513-205f3113327c)

**Comment by Xi-Plus** [comment]
Hi, @snb0169. Thanks for your feedback. I have fixed it in 0f90ffda043c3d764462bbdbe836fae698064550 and it works on YouTube now. Can you try it again?
